### PR TITLE
refactor: Using async await on fruits find #12

### PR DESCRIPTION
**Pull request by ANNPATIL**

### CODE REVIEW

**Comment by helio-frota** [comment]
@ANNPATIL the code is looking good, but can you please fix the eslint errors?
You can see the errors when you run `npm install`

**Comment by ANNPATIL** [comment]
OK now i corrected that

**Comment by helio-frota** [comment]
Can you please update the `package.json` file adding `--fix` to eslint ?

before:
`"postinstall": "eslint --ignore-path .gitignore .",`

after:
"postinstall": "eslint --fix --ignore-path .gitignore .",

Then you can run `npm install` 
Then `git add .`
`git commit --amend` 
`git push origin find --force`

**Comment by helio-frota** [comment]
@ANNPATIL great thanks!

**Pull request merged**
